name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: cd workspace/tips && make build && cd -

    - name: Test
      run: cd workspace/tips && make test && cd -
